# Generated by Django 5.2.7 on 2025-11-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opti_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteration',
            name='line_search',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
